# Generated by Django 4.2.30 on 2026-06-05 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0003_profile_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='resume_text',
            field=models.TextField(blank=True),
        ),
    ]
