# Generated by Django 4.2.30 on 2026-06-02 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
        ('jobs_app', '0002_alter_applicationmodel_applicant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationmodel',
            name='applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users_app.usermodel'),
        ),
    ]
