# Generated by Django 4.2.30 on 2026-06-04 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0005_alter_applicationmodel_applicant'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmodel',
            name='minimum_score',
            field=models.IntegerField(default=0),
        ),
    ]
