# Generated by Django 4.2.30 on 2026-06-04 10:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs_app', '0006_jobmodel_minimum_score'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='applicationmodel',
            unique_together={('job', 'applicant')},
        ),
    ]
