# Generated by Django 4.2.30 on 2026-06-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0011_interviewscorecardmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationmodel',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('assessment', 'Online Assessment'), ('technical', 'Technical Interview'), ('hr', 'HR Round'), ('offered', 'Offer Extended'), ('rejected', 'Rejected')], default='applied', max_length=25),
        ),
    ]
